apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vbvwxj5ls-nodejs 
  janus-idp.io/tekton: vbvwxj5ls-nodejs
  backstage.io/kubernetes-id: vbvwxj5ls-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vbvwxj5ls-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml